using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Conquer_Online_Server.Client;
using Conquer_Online_Server.Game.Attacking;
using Conquer_Online_Server.Network.GamePackets;

namespace Conquer_Online_Server.Effect
{
    public class BahaaEffects
    {
        #region All Effects
        public static void cortege(GameClient client) { client.Entity.Update(_String.Effect, "cortege", true); }
        public static void the_wes_03low(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_03low", true); }
        public static void the_wes_04hig(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_04hig", true); }
        public static void the_wes_04lowd(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_04low", true); }
        public static void the_wes_05hig(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_05hig", true); }
        public static void the_wes_05low(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_05low", true); }
        public static void hdhththt(GameClient client) { client.Entity.Update(_String.Effect, "900269", true); }
        public static void hoo_01_hig(GameClient client) { client.Entity.Update(_String.Effect, "hoo_01_hig", true); }
        public static void hoo_01_low(GameClient client) { client.Entity.Update(_String.Effect, "hoo_01_low", true); }
        public static void hoo_02_hig(GameClient client) { client.Entity.Update(_String.Effect, "hoo_02_hig", true); }
        public static void hoo_02_low(GameClient client) { client.Entity.Update(_String.Effect, "hoo_02_low", true); }
        public static void hoo_03_hig(GameClient client) { client.Entity.Update(_String.Effect, "hoo_03_hig", true); }
        public static void Magicflying1(GameClient client) { client.Entity.Update(_String.Effect, "Magicflying1-1", true); }
        public static void Magicflying12(GameClient client) { client.Entity.Update(_String.Effect, "Magicflying1-2", true); }
        public static void Magicflying21(GameClient client) { client.Entity.Update(_String.Effect, "Magicflying2-1", true); }
        public static void Magicflying22(GameClient client) { client.Entity.Update(_String.Effect, "Magicflying2-2", true); }
        public static void Magicflying31(GameClient client) { client.Entity.Update(_String.Effect, "Magicflying3-1", true); }
        public static void Magicflying32(GameClient client) { client.Entity.Update(_String.Effect, "Magicflying3-2", true); }
        public static void pir_roe_01hig(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_01hig", true); }
        public static void pir_roe_01low(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_01low", true); }
        public static void pir_roe_02hig(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_02hig", true); }
        public static void pir_roe_02low(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_02low", true); }
        public static void pir_roe_03hig(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_03hig", true); }
        public static void pir_roe_03low(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_03low", true); }
        public static void pir_roe_04hig(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_04hig", true); }
        public static void pir_roe_04low(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_04low", true); }
        public static void pir_roe_05hig(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_05hig", true); }
        public static void pir_roe_05low(GameClient client) { client.Entity.Update(_String.Effect, "pir_roe_05low", true); }
        public static void the_wes_01hig(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_01hig", true); }
        public static void the_wes_01low(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_01low", true); }
        public static void the_wes_02hig(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_02hig", true); }
        public static void the_wes_02low(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_02low", true); }
        public static void the_wes_03hig(GameClient client) { client.Entity.Update(_String.Effect, "the_wes_03hig", true); }
        public static void MapleFores(GameClient client) { client.Entity.Update(_String.Effect, "MapleFores", true); }
        public static void Market(GameClient client) { client.Entity.Update(_String.Effect, "Market", true); }
        public static void monster(GameClient client) { client.Entity.Update(_String.Effect, "monster", true); }
        public static void MoonSprin(GameClient client) { client.Entity.Update(_String.Effect, "MoonSprin", true); }
        public static void n_arrow(GameClient client) { client.Entity.Update(_String.Effect, "n-arrow", true); }
        public static void noconfirm(GameClient client) { client.Entity.Update(_String.Effect, "noconfirm", true); }
        public static void other(GameClient client) { client.Entity.Update(_String.Effect, "other", true); }
        public static void perfect(GameClient client) { client.Entity.Update(_String.Effect, "perfect", true); }
        public static void PhoenixCity(GameClient client) { client.Entity.Update(_String.Effect, "PhoenixCity", true); }
        public static void QiXingGao(GameClient client) { client.Entity.Update(_String.Effect, "QiXingGao", true); }
        public static void ReedIsland(GameClient client) { client.Entity.Update(_String.Effect, "ReedIsland", true); }
        public static void reif(GameClient client) { client.Entity.Update(_String.Effect, "reif", true); }
        public static void role(GameClient client) { client.Entity.Update(_String.Effect, "role", true); }
        public static void SanYangKai(GameClient client) { client.Entity.Update(_String.Effect, "SanYangKai", true); }
        public static void scene(GameClient client) { client.Entity.Update(_String.Effect, "scene", true); }
        public static void clewarbig(GameClient client) { client.Entity.Update(_String.Effect, "clewarbig", true); }
        public static void clewarsma(GameClient client) { client.Entity.Update(_String.Effect, "clewarsma", true); }
        public static void scene_FF(GameClient client) { client.Entity.Update(_String.Effect, "scene-FF", true); }
        public static void ShiQuanShi(GameClient client) { client.Entity.Update(_String.Effect, "ShiQuanShi", true); }
        public static void SiJiPingAn(GameClient client) { client.Entity.Update(_String.Effect, "SiJiPingAn", true); }
        public static void skill(GameClient client) { client.Entity.Update(_String.Effect, "skill", true); }
        public static void TwinCity(GameClient client) { client.Entity.Update(_String.Effect, "TwinCity", true); }
        public static void WaterfallCa(GameClient client) { client.Entity.Update(_String.Effect, "WaterfallCa", true); }
        public static void weapon(GameClient client) { client.Entity.Update(_String.Effect, "weapon", true); }
        public static void WindPlain(GameClient client) { client.Entity.Update(_String.Effect, "WindPlain", true); }
        public static void Wonderlan(GameClient client) { client.Entity.Update(_String.Effect, "Wonderlan", true); }
        public static void swordcaromstart03(GameClient client) { client.Entity.Update(_String.Effect, "swordcaromstart03", true); }
        public static void swordcaromstart04(GameClient client) { client.Entity.Update(_String.Effect, "swordcaromstart04", true); }
        public static void swordcaromstart05(GameClient client) { client.Entity.Update(_String.Effect, "swordcaromstart05", true); }
        public static void tal_att_flf(GameClient client) { client.Entity.Update(_String.Effect, "tal_att_flf", true); }
        public static void Rab_Est_app5(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app5", true); }
        public static void Rab_Est_app6(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app6", true); }
        public static void Rab_Est_app7(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app7", true); }
        public static void Rab_Est_app8(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app8", true); }
        public static void sou_swo_sta(GameClient client) { client.Entity.Update(_String.Effect, "sou_swo_sta", true); }
        public static void poisoncast05(GameClient client) { client.Entity.Update(_String.Effect, "poisoncast05", true); }
        public static void poisonfog01(GameClient client) { client.Entity.Update(_String.Effect, "poisonfog01", true); }
        public static void poisonfog02(GameClient client) { client.Entity.Update(_String.Effect, "poisonfog02", true); }
        public static void poisonfog03(GameClient client) { client.Entity.Update(_String.Effect, "poisonfog03", true); }
        public static void poisoncast(GameClient client) { client.Entity.Update(_String.Effect, "poisoncast", true); }
        public static void die_paa_acc(GameClient client) { client.Entity.Update(_String.Effect, "die_paa_acc", true); }
        public static void die_paa_ass(GameClient client) { client.Entity.Update(_String.Effect, "die_paa_ass", true); }
        public static void dispersion(GameClient client) { client.Entity.Update(_String.Effect, "dispersion", true); }
        public static void endurexp(GameClient client) { client.Entity.Update(_String.Effect, "endurexp", true); }
        public static void Rab_Est_att(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_att", true); }
        public static void Rab_Est_app1(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app1", true); }
        public static void int_fir_acc(GameClient client) { client.Entity.Update(_String.Effect, "int_fir_acc", true); }
        public static void int_fir_ass(GameClient client) { client.Entity.Update(_String.Effect, "int_fir_ass", true); }
        public static void int_fir_muz(GameClient client) { client.Entity.Update(_String.Effect, "int_fir_muz", true); }
        public static void KillerPattern(GameClient client) { client.Entity.Update(_String.Effect, "KillerPattern", true); }
        public static void Thunderbolt(GameClient client) { client.Entity.Update(_String.Effect, "Thunderbolt", true); }
        public static void ScapegoatSwitchOpen(GameClient client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen", true); }
        public static void zf2_e129break_a(GameClient client) { client.Entity.Update(_String.Effect, "zf2-e129break_a", true); }
        public static void endureXPwordq(GameClient client) { client.Entity.Update(_String.Effect, "endureXPwordq", true); }
        public static void ScapegoatSwitchOpen02(GameClient client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen02", true); }
        public static void zf2_e181(GameClient client) { client.Entity.Update(_String.Effect, "zf2-e181", true); }
        public static void endureXPappear(GameClient client) { client.Entity.Update(_String.Effect, "endureXPappear", true); }
        public static void endureXPattac(GameClient client) { client.Entity.Update(_String.Effect, "endureXPattac", true); }
        public static void endureXPbing(GameClient client) { client.Entity.Update(_String.Effect, "endureXPbing", true); }
        public static void Rab_Est_cyc0(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_cyc0", true); }
        public static void endureXPdeat(GameClient client) { client.Entity.Update(_String.Effect, "endureXPdeat", true); }
        public static void RapidReplace(GameClient client) { client.Entity.Update(_String.Effect, "RapidReplace", true); }
        public static void endureXPdisa(GameClient client) { client.Entity.Update(_String.Effect, "endureXPdisa", true); }
        public static void poisonparoxy(GameClient client) { client.Entity.Update(_String.Effect, "poisonparoxy", true); }
        public static void endureXPscre(GameClient client) { client.Entity.Update(_String.Effect, "endureXPscre", true); }
        public static void replaceappear(GameClient client) { client.Entity.Update(_String.Effect, "replaceappear", true); }
        public static void endureXPstate(GameClient client) { client.Entity.Update(_String.Effect, "endureXPstate", true); }
        public static void endureXPswor(GameClient client) { client.Entity.Update(_String.Effect, "endureXPswor", true); }
        public static void endureXPwor(GameClient client) { client.Entity.Update(_String.Effect, "endureXPwor", true); }
        public static void replacedisappe(GameClient client) { client.Entity.Update(_String.Effect, "replacedisappe", true); }
        public static void WuFuLinMe(GameClient client) { client.Entity.Update(_String.Effect, "WuFuLinMe", true); }
        public static void replacedisapp(GameClient client) { client.Entity.Update(_String.Effect, "replacedisapp", true); }
        public static void YiFanFengS(GameClient client) { client.Entity.Update(_String.Effect, "YiFanFengS", true); }
        public static void endureXPword(GameClient client) { client.Entity.Update(_String.Effect, "endureXPword", true); }
        public static void zf2_e067(GameClient client) { client.Entity.Update(_String.Effect, "zf2-e067", true); }
        public static void zf2_e128(GameClient client) { client.Entity.Update(_String.Effect, "zf2-e128", true); }
        public static void ScapegoatSwi(GameClient client) { client.Entity.Update(_String.Effect, "ScapegoatSwi", true); }
        public static void zf2_e129(GameClient client) { client.Entity.Update(_String.Effect, "zf2-e129", true); }
        public static void cyclonehanddart02(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehanddart02", true); }
        public static void poisonblast03(GameClient client) { client.Entity.Update(_String.Effect, "poisonblast03", true); }
        public static void perfect2(GameClient client) { client.Entity.Update(_String.Effect, "perfect", true); }
        public static void cyclonehanddart03(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehanddart03", true); }
        public static void poisonblast04(GameClient client) { client.Entity.Update(_String.Effect, "poisonblast04", true); }
        public static void cyclonehanddart04(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehanddart04", true); }
        public static void poisonblast05(GameClient client) { client.Entity.Update(_String.Effect, "poisonblast05", true); }
        public static void QiXingGaoat(GameClient client) { client.Entity.Update(_String.Effect, "QiXingGaoat", true); }
        public static void cyclonehanddart05(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehanddart05", true); }
        public static void cyclonehandend(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandend", true); }
        public static void Rab_Est_app2(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app2", true); }
        public static void cyclonehandend02(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandend02", true); }
        public static void poisoncast03(GameClient client) { client.Entity.Update(_String.Effect, "poisoncast03", true); }
        public static void cyclonehandend05(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandend05", true); }
        public static void poisoncast0(GameClient client) { client.Entity.Update(_String.Effect, "poisoncast0", true); }
        public static void poisonfog04(GameClient client) { client.Entity.Update(_String.Effect, "poisonfog04", true); }
        public static void endureXPattack(GameClient client) { client.Entity.Update(_String.Effect, "endureXPattack", true); }
        public static void SiJiPingAnat(GameClient client) { client.Entity.Update(_String.Effect, "SiJiPingAnat", true); }
        public static void endureXPdeath(GameClient client) { client.Entity.Update(_String.Effect, "endureXPdeath", true); }
        public static void attach_discharge04(GameClient client) { client.Entity.Update(_String.Effect, "attach_discharge04", true); }
        public static void attach_discharge05(GameClient client) { client.Entity.Update(_String.Effect, "attach_discharge05", true); }
        public static void mag_pro_sta(GameClient client) { client.Entity.Update(_String.Effect, "mag_pro_sta", true); }
        public static void attach_fly(GameClient client) { client.Entity.Update(_String.Effect, "attach_fly", true); }
        public static void meteor(GameClient client) { client.Entity.Update(_String.Effect, "meteor", true); }
        public static void attach_fly02(GameClient client) { client.Entity.Update(_String.Effect, "attach_fly02", true); }
        public static void Meteorflash(GameClient client) { client.Entity.Update(_String.Effect, "Meteorflash", true); }
        public static void attach_fly03(GameClient client) { client.Entity.Update(_String.Effect, "attach_fly03", true); }
        public static void nag_bom_acc(GameClient client) { client.Entity.Update(_String.Effect, "nag_bom_acc", true); }
        public static void attach_fly04(GameClient client) { client.Entity.Update(_String.Effect, "attach_fly04", true); }
        public static void nag_bom_ass(GameClient client) { client.Entity.Update(_String.Effect, "nag_bom_ass", true); }
        public static void attach_fly05(GameClient client) { client.Entity.Update(_String.Effect, "attach_fly05", true); }
        public static void poisonattack(GameClient client) { client.Entity.Update(_String.Effect, "poisonattack", true); }
        public static void Bladefrost(GameClient client) { client.Entity.Update(_String.Effect, "Bladefrost", true); }
        public static void poisonattack02(GameClient client) { client.Entity.Update(_String.Effect, "poisonattack02", true); }
        public static void blo_sic_lig(GameClient client) { client.Entity.Update(_String.Effect, "blo_sic_lig", true); }
        public static void poisonattack03(GameClient client) { client.Entity.Update(_String.Effect, "poisonattack03", true); }
        public static void break_accept(GameClient client) { client.Entity.Update(_String.Effect, "break_accept", true); }
        public static void poisonattack04(GameClient client) { client.Entity.Update(_String.Effect, "poisonattack04", true); }
        public static void break_accept02(GameClient client) { client.Entity.Update(_String.Effect, "break_accept02", true); }
        public static void poisonattack05(GameClient client) { client.Entity.Update(_String.Effect, "poisonattack05", true); }
        public static void acc_ass_bul(GameClient client) { client.Entity.Update(_String.Effect, "acc_ass_bul", true); }
        public static void cyclonehanddart(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehanddart", true); }
        public static void poisonblast02(GameClient client) { client.Entity.Update(_String.Effect, "poisonblast02", true); }
        public static void ScapegoatSwitchOpen03(GameClient client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen03", true); }
        public static void acc_ass_muz(GameClient client) { client.Entity.Update(_String.Effect, "acc_ass_muz", true); }
        public static void pro_tir_sta(GameClient client) { client.Entity.Update(_String.Effect, "pro_tir_sta", true); }
        public static void acc_fir_acc(GameClient client) { client.Entity.Update(_String.Effect, "acc_fir_acc", true); }
        public static void Rab_Est_acc(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_acc", true); }
        public static void Assassin(GameClient client) { client.Entity.Update(_String.Effect, "Assassin", true); }
        public static void Rab_Est_app0(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app0", true); }
        public static void attach_accept(GameClient client) { client.Entity.Update(_String.Effect, "attach_accept", true); }
        public static void attach_accept02(GameClient client) { client.Entity.Update(_String.Effect, "attach_accept02", true); }
        public static void goose(GameClient client) { client.Entity.Update(_String.Effect, "goose", true); }
        public static void swordcaromaccept(GameClient client) { client.Entity.Update(_String.Effect, "swordcaromaccept", true); }
        public static void attach_accept03(GameClient client) { client.Entity.Update(_String.Effect, "attach_accept03", true); }
        public static void Rab_Est_app3(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app3", true); }
        public static void attach_accept04(GameClient client) { client.Entity.Update(_String.Effect, "attach_accept04", true); }
        public static void Rab_Est_app4(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app4", true); }
        public static void attach_accept05(GameClient client) { client.Entity.Update(_String.Effect, "attach_accept05", true); }
        public static void attach_continuance02(GameClient client) { client.Entity.Update(_String.Effect, "attach_continuance02", true); }
        public static void attach_continuance03(GameClient client) { client.Entity.Update(_String.Effect, "attach_continuance03", true); }
        public static void attach_continuance04(GameClient client) { client.Entity.Update(_String.Effect, "attach_continuance04", true); }
        public static void attach_continuance05(GameClient client) { client.Entity.Update(_String.Effect, "attach_continuance05", true); }
        public static void Rab_Est_app9(GameClient client) { client.Entity.Update(_String.Effect, "Rab_Est_app9", true); }
        public static void attach_discharge(GameClient client) { client.Entity.Update(_String.Effect, "attach_discharge", true); }
        public static void KOTeleport(GameClient client) { client.Entity.Update(_String.Effect, "KOTeleport", true); }
        public static void attach_discharge02(GameClient client) { client.Entity.Update(_String.Effect, "attach_discharge02", true); }
        public static void let_gun_sho(GameClient client) { client.Entity.Update(_String.Effect, "let_gun_sho", true); }
        public static void WarFlagEscortBegin(GameClient client) { client.Entity.Update(_String.Effect, "WarFlagEscortBegin", true); }
        public static void attach_discharge03(GameClient client) { client.Entity.Update(_String.Effect, "attach_discharge03", true); }
        public static void mag_pro_ari(GameClient client) { client.Entity.Update(_String.Effect, "mag_pro_ari", true); }
        public static void cyclonehand04(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehand04", true); }
        public static void mag_pro_rep(GameClient client) { client.Entity.Update(_String.Effect, "mag_pro_rep", true); }
        public static void cyclonehand05(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehand05", true); }
        public static void poisonparoxysm03(GameClient client) { client.Entity.Update(_String.Effect, "poisonparoxysm03", true); }
        public static void cyclonehandattack(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandattack", true); }
        public static void poisonparoxysm04(GameClient client) { client.Entity.Update(_String.Effect, "poisonparoxysm04", true); }
        public static void cyclonehandattack02(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandattack02", true); }
        public static void poisonparoxysm05(GameClient client) { client.Entity.Update(_String.Effect, "poisonparoxysm05", true); }
        public static void cyclonehandattack2(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandattack2", true); }
        public static void poisonstate02(GameClient client) { client.Entity.Update(_String.Effect, "poisonstate02", true); }
        public static void cyclonehandattack05(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandattack05", true); }
        public static void poisonstate03(GameClient client) { client.Entity.Update(_String.Effect, "poisonstate03", true); }
        public static void cyclonehandcycle(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandcycle", true); }
        public static void poisonstate04(GameClient client) { client.Entity.Update(_String.Effect, "poisonstate04", true); }
        public static void cyclonehandcycle02(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandcycle02", true); }
        public static void poisonstate05(GameClient client) { client.Entity.Update(_String.Effect, "poisonstate05", true); }
        public static void cyclonehandcycle03(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandcycle03", true); }
        public static void pro_gre_assbom(GameClient client) { client.Entity.Update(_String.Effect, "pro_gre_assbom", true); }
        public static void cyclonehandcycle04(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandcycle04", true); }
        public static void pro_gre_assflo(GameClient client) { client.Entity.Update(_String.Effect, "pro_gre_assflo", true); }
        public static void cyclonehandcycle05(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehandcycle05", true); }
        public static void pro_tir_assbom(GameClient client) { client.Entity.Update(_String.Effect, "pro_tir_assbom", true); }
        public static void break_accept03(GameClient client) { client.Entity.Update(_String.Effect, "break_accept03", true); }
        public static void endureXPwordzai(GameClient client) { client.Entity.Update(_String.Effect, "endureXPwordzai", true); }
        public static void pro_tir_assflo(GameClient client) { client.Entity.Update(_String.Effect, "pro_tir_assflo", true); }
        public static void break_accept04(GameClient client) { client.Entity.Update(_String.Effect, "break_accept04", true); }
        public static void endureXPwordzhe(GameClient client) { client.Entity.Update(_String.Effect, "endureXPwordzhe", true); }
        public static void ScapegoatSwitchOpen04(GameClient client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen04", true); }
        public static void break_accept05(GameClient client) { client.Entity.Update(_String.Effect, "break_accept05", true); }
        public static void endureXPwordzhen(GameClient client) { client.Entity.Update(_String.Effect, "endureXPwordzhen", true); }
        public static void ScapegoatSwitchOpen05(GameClient client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen05", true); }
        public static void break_start(GameClient client) { client.Entity.Update(_String.Effect, "break_start", true); }
        public static void EquipBroken(GameClient client) { client.Entity.Update(_String.Effect, "EquipBroken", true); }
        public static void sea(GameClient client) { client.Entity.Update(_String.Effect, "sea", true); }
        public static void break_start02(GameClient client) { client.Entity.Update(_String.Effect, "break_start02", true); }
        public static void gainTeleport(GameClient client) { client.Entity.Update(_String.Effect, "gainTeleport", true); }
        public static void break_start03(GameClient client) { client.Entity.Update(_String.Effect, "break_start03", true); }
        public static void poisoncast02(GameClient client) { client.Entity.Update(_String.Effect, "poisoncast02", true); }
        public static void break_start04(GameClient client) { client.Entity.Update(_String.Effect, "break_start04", true); }
        public static void gro_wea_tor(GameClient client) { client.Entity.Update(_String.Effect, "gro_wea_tor", true); }
        public static void swordcaromstart(GameClient client) { client.Entity.Update(_String.Effect, "swordcaromstart", true); }
        public static void break_track(GameClient client) { client.Entity.Update(_String.Effect, "break_track", true); }
        public static void Icearray(GameClient client) { client.Entity.Update(_String.Effect, "Icearray", true); }
        public static void swordcaromstart02(GameClient client) { client.Entity.Update(_String.Effect, "swordcaromstart02", true); }
        public static void break_track02(GameClient client) { client.Entity.Update(_String.Effect, "break_track02", true); }
        public static void break_track03(GameClient client) { client.Entity.Update(_String.Effect, "break_track03", true); }
        public static void break_track04(GameClient client) { client.Entity.Update(_String.Effect, "break_track04", true); }
        public static void break_track05(GameClient client) { client.Entity.Update(_String.Effect, "break_track05", true); }
        public static void bump2(GameClient client) { client.Entity.Update(_String.Effect, "bump2", true); }
        public static void Knifespin(GameClient client) { client.Entity.Update(_String.Effect, "Knifespin", true); }
        public static void tempest(GameClient client) { client.Entity.Update(_String.Effect, "tempest", true); }
        public static void cyclonehand(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehand", true); }
        public static void poisonfog05(GameClient client) { client.Entity.Update(_String.Effect, "poisonfog05", true); }
        public static void cyclonehand02(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehand02", true); }
        public static void poisonmiss(GameClient client) { client.Entity.Update(_String.Effect, "poisonmiss", true); }
        public static void cyclonehand03(GameClient client) { client.Entity.Update(_String.Effect, "cyclonehand03", true); }
        public static void poisonorigin(GameClient client) { client.Entity.Update(_String.Effect, "poisonorigin", true); }
        public static void scene_goon(GameClient client) { client.Entity.Update(_String.Effect, "scene_goon", true); }
        public static void flower3(GameClient client) { client.Entity.Update(_String.Effect, "flower3", true); }
        public static void horse_aff(GameClient client) { client.Entity.Update(_String.Effect, "horse_aff", true); }
        public static void horse_back(GameClient client) { client.Entity.Update(_String.Effect, "horse_back", true); }
        public static void horse_run(GameClient client) { client.Entity.Update(_String.Effect, "horse_run", true); }
        public static void ridmatch_colon(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_colon", true); }
        public static void ridmatch_eighth(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_eighth", true); }
        public static void ridmatch_fifth(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_fifth", true); }
        public static void ridmatch_first(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_first", true); }
        public static void ridmatch_fourth(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_fourth", true); }
        public static void ridmatch_ninth(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_ninth", true); }
        public static void bossimmunity(GameClient client) { client.Entity.Update(_String.Effect, "bossimmunity", true); }
        public static void ridmatch_num0(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num0", true); }
        public static void ridmatch_num1(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num1", true); }
        public static void ridmatch_num2(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num2", true); }
        public static void ridmatch_num3(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num3", true); }
        public static void ridmatch_num4(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num4", true); }
        public static void ridmatch_num5(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num5", true); }
        public static void ridmatch_num6(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num6", true); }
        public static void ridmatch_num7(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num7", true); }
        public static void ridmatch_num8(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num8", true); }
        public static void ridmatch_num9(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_num9", true); }
        public static void ridmatch_second(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_second", true); }
        public static void ridmatch_seventh(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_seventh", true); }
        public static void ridmatch_sixth(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_sixth", true); }
        public static void ridmatch_tenth(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_tenth", true); }
        public static void ridmatch_third(GameClient client) { client.Entity.Update(_String.Effect, "ridmatch_third", true); }
        public static void scene_app(GameClient client) { client.Entity.Update(_String.Effect, "scene_app", true); }
        public static void scene_dis(GameClient client) { client.Entity.Update(_String.Effect, "scene_dis", true); }
        public static void balloon1(GameClient client) { client.Entity.Update(_String.Effect, "balloon1", true); }
        public static void balloon2(GameClient client) { client.Entity.Update(_String.Effect, "balloon2", true); }
        public static void balloon3(GameClient client) { client.Entity.Update(_String.Effect, "balloon3", true); }
        public static void balloon4(GameClient client) { client.Entity.Update(_String.Effect, "balloon4", true); }
        public static void ff02(GameClient client) { client.Entity.Update(_String.Effect, "ff02", true); }
        public static void ff03(GameClient client) { client.Entity.Update(_String.Effect, "ff03", true); }
        public static void ff04(GameClient client) { client.Entity.Update(_String.Effect, "ff04", true); }
        public static void ff05(GameClient client) { client.Entity.Update(_String.Effect, "ff05", true); }
        public static void ff07(GameClient client) { client.Entity.Update(_String.Effect, "ff07", true); }
        public static void ff08(GameClient client) { client.Entity.Update(_String.Effect, "ff08", true); }
        public static void ff09(GameClient client) { client.Entity.Update(_String.Effect, "ff09", true); }
        public static void ff12(GameClient client) { client.Entity.Update(_String.Effect, "ff12", true); }
        public static void ff13(GameClient client) { client.Entity.Update(_String.Effect, "ff13", true); }
        public static void ff14(GameClient client) { client.Entity.Update(_String.Effect, "ff14", true); }
        public static void ff15(GameClient client) { client.Entity.Update(_String.Effect, "ff15", true); }
        public static void ff16(GameClient client) { client.Entity.Update(_String.Effect, "ff16", true); }
        public static void ff17(GameClient client) { client.Entity.Update(_String.Effect, "ff17", true); }
        public static void ff18(GameClient client) { client.Entity.Update(_String.Effect, "ff18", true); }
        public static void ff18a(GameClient client) { client.Entity.Update(_String.Effect, "ff18a", true); }
        public static void ff18b(GameClient client) { client.Entity.Update(_String.Effect, "ff18b", true); }
        public static void ff19(GameClient client) { client.Entity.Update(_String.Effect, "ff19", true); }
        public static void ff20(GameClient client) { client.Entity.Update(_String.Effect, "ff20", true); }
        public static void ff21(GameClient client) { client.Entity.Update(_String.Effect, "ff21", true); }
        public static void ff22(GameClient client) { client.Entity.Update(_String.Effect, "ff22", true); }
        public static void ff23(GameClient client) { client.Entity.Update(_String.Effect, "ff23", true); }
        public static void flower1(GameClient client) { client.Entity.Update(_String.Effect, "flower1", true); }
        public static void flower2(GameClient client) { client.Entity.Update(_String.Effect, "flower2", true); }
        public static void interface215(GameClient client) { client.Entity.Update(_String.Effect, "interface215", true); }
        public static void interface216(GameClient client) { client.Entity.Update(_String.Effect, "interface216", true); }
        public static void keepon(GameClient client) { client.Entity.Update(_String.Effect, "keepon", true); }
        public static void KOfire01(GameClient client) { client.Entity.Update(_String.Effect, "KOfire01", true); }
        public static void listlock(GameClient client) { client.Entity.Update(_String.Effect, "listlock", true); }
        public static void PKpack(GameClient client) { client.Entity.Update(_String.Effect, "PKpack", true); }
        public static void PKpack_s(GameClient client) { client.Entity.Update(_String.Effect, "PKpack_s", true); }
        public static void pkpunish(GameClient client) { client.Entity.Update(_String.Effect, "pkpunish", true); }
        public static void roleword(GameClient client) { client.Entity.Update(_String.Effect, "roleword", true); }
        public static void XP(GameClient client) { client.Entity.Update(_String.Effect, "XP", true); }
        public static void fusebijou04(GameClient client) { client.Entity.Update(_String.Effect, "fusebijou04", true); }
        public static void fusebijou05(GameClient client) { client.Entity.Update(_String.Effect, "fusebijou05", true); }
        public static void fusebijou06(GameClient client) { client.Entity.Update(_String.Effect, "fusebijou06", true); }
        public static void fusebijou07(GameClient client) { client.Entity.Update(_String.Effect, "fusebijou07", true); }
        public static void fusesucceed(GameClient client) { client.Entity.Update(_String.Effect, "fusesucceed", true); }
        public static void GemComposeFull(GameClient client) { client.Entity.Update(_String.Effect, "GemComposeFull", true); }
        public static void GemComposeSuc700001(GameClient client) { client.Entity.Update(_String.Effect, "GemComposeSuc700001", true); }
        public static void interface195(GameClient client) { client.Entity.Update(_String.Effect, "interface195", true); }
        public static void interface196(GameClient client) { client.Entity.Update(_String.Effect, "interface196", true); }
        public static void interface197(GameClient client) { client.Entity.Update(_String.Effect, "interface197", true); }
        public static void interface198(GameClient client) { client.Entity.Update(_String.Effect, "interface198", true); }
        public static void interface199(GameClient client) { client.Entity.Update(_String.Effect, "interface199", true); }
        public static void interface200(GameClient client) { client.Entity.Update(_String.Effect, "interface200", true); }
        public static void interface201(GameClient client) { client.Entity.Update(_String.Effect, "interface201", true); }
        public static void interface202(GameClient client) { client.Entity.Update(_String.Effect, "interface202", true); }
        public static void interface203(GameClient client) { client.Entity.Update(_String.Effect, "interface203", true); }
        public static void interface204(GameClient client) { client.Entity.Update(_String.Effect, "interface204", true); }
        public static void interface205(GameClient client) { client.Entity.Update(_String.Effect, "interface205", true); }
        public static void interface206(GameClient client) { client.Entity.Update(_String.Effect, "interface206", true); }
        public static void interface207(GameClient client) { client.Entity.Update(_String.Effect, "interface207", true); }
        public static void interface208(GameClient client) { client.Entity.Update(_String.Effect, "interface208", true); }
        public static void interface209(GameClient client) { client.Entity.Update(_String.Effect, "interface209", true); }
        public static void interface210(GameClient client) { client.Entity.Update(_String.Effect, "interface210", true); }
        public static void interface211(GameClient client) { client.Entity.Update(_String.Effect, "interface211", true); }
        public static void interface212(GameClient client) { client.Entity.Update(_String.Effect, "interface212", true); }
        public static void interface213(GameClient client) { client.Entity.Update(_String.Effect, "interface213", true); }
        public static void interface214(GameClient client) { client.Entity.Update(_String.Effect, "interface214", true); }
        public static void alternation(GameClient client) { client.Entity.Update(_String.Effect, "alternation", true); }
        public static void award_res(GameClient client) { client.Entity.Update(_String.Effect, "award_res", true); }
        public static void box_preview(GameClient client) { client.Entity.Update(_String.Effect, "box_preview", true); }
        public static void box_weapon(GameClient client) { client.Entity.Update(_String.Effect, "box_weapon", true); }
        public static void card_AllIn_cyc(GameClient client) { client.Entity.Update(_String.Effect, "card_AllIn_cyc", true); }
        public static void card_arrowhead(GameClient client) { client.Entity.Update(_String.Effect, "card_arrowhead", true); }
        public static void card_banner(GameClient client) { client.Entity.Update(_String.Effect, "card_banner", true); }
        public static void card_beacon(GameClient client) { client.Entity.Update(_String.Effect, "card_beacon", true); }
        public static void card_call_cyc(GameClient client) { client.Entity.Update(_String.Effect, "card_call_cyc", true); }
        public static void card_Check(GameClient client) { client.Entity.Update(_String.Effect, "card_Check", true); }
        public static void card_Fold_cyc(GameClient client) { client.Entity.Update(_String.Effect, "card_Fold_cyc", true); }
        public static void card_lose(GameClient client) { client.Entity.Update(_String.Effect, "card_lose", true); }
        public static void card_loseall(GameClient client) { client.Entity.Update(_String.Effect, "card_loseall", true); }
        public static void card_Raise_cyc(GameClient client) { client.Entity.Update(_String.Effect, "card_Raise_cyc", true); }
        public static void card_win(GameClient client) { client.Entity.Update(_String.Effect, "card_win", true); }
        public static void chatclosebtn(GameClient client) { client.Entity.Update(_String.Effect, "chatclosebtn", true); }
        public static void compose(GameClient client) { client.Entity.Update(_String.Effect, "compose", true); }
        public static void dsoulaffuse(GameClient client) { client.Entity.Update(_String.Effect, "dsoulaffuse", true); }
        public static void eqpdownlevitf(GameClient client) { client.Entity.Update(_String.Effect, "eqpdownlevitf", true); }
        public static void equip_function(GameClient client) { client.Entity.Update(_String.Effect, "equip_function", true); }
        public static void equip_openhole(GameClient client) { client.Entity.Update(_String.Effect, "equip_openhole", true); }
        public static void EquipAppend(GameClient client) { client.Entity.Update(_String.Effect, "EquipAppend", true); }
        public static void equiprebuild(GameClient client) { client.Entity.Update(_String.Effect, "equiprebuild", true); }
        public static void expression(GameClient client) { client.Entity.Update(_String.Effect, "expression", true); }
        public static void fusebijou01(GameClient client) { client.Entity.Update(_String.Effect, "fusebijou01", true); }
        public static void fusebijou02(GameClient client) { client.Entity.Update(_String.Effect, "fusebijou02", true); }
        public static void fusebijou03(GameClient client) { client.Entity.Update(_String.Effect, "fusebijou03", true); }
        public static void firecracker_(GameClient client) { client.Entity.Update(_String.Effect, "firecracker-", true); }
        public static void flash(GameClient client) { client.Entity.Update(_String.Effect, "flash", true); }
        public static void foot01(GameClient client) { client.Entity.Update(_String.Effect, "foot01", true); }
        public static void foot_xin(GameClient client) { client.Entity.Update(_String.Effect, "foot-xin", true); }
        public static void good(GameClient client) { client.Entity.Update(_String.Effect, "good", true); }
        public static void PKItemRewardEffect(GameClient client) { client.Entity.Update(_String.Effect, "PKItemRewardEffect", true); }
        public static void hunpo02(GameClient client) { client.Entity.Update(_String.Effect, "hunpo02", true); }
        public static void JiuJiuTongX2(GameClient client) { client.Entity.Update(_String.Effect, "JiuJiuTongX", true); }
        public static void KylinCave(GameClient client) { client.Entity.Update(_String.Effect, "KylinCave", true); }
        public static void placardbtnclew(GameClient client) { client.Entity.Update(_String.Effect, "placardbtnclew", true); }
        public static void lightsword(GameClient client) { client.Entity.Update(_String.Effect, "lightsword", true); }
        public static void LiuLiuDaSh(GameClient client) { client.Entity.Update(_String.Effect, "LiuLiuDaSh", true); }
        public static void LoveCanyo(GameClient client) { client.Entity.Update(_String.Effect, "LoveCanyo", true); }
        public static void LuckAbsorb(GameClient client) { client.Entity.Update(_String.Effect, "LuckAbsorb", true); }
        public static void LuckDiffuse(GameClient client) { client.Entity.Update(_String.Effect, "LuckDiffuse", true); }
        public static void Lucky(GameClient client) { client.Entity.Update(_String.Effect, "Lucky", true); }
        public static void LuckyGuy(GameClient client) { client.Entity.Update(_String.Effect, "LuckyGuy", true); }
        public static void magic(GameClient client) { client.Entity.Update(_String.Effect, "magic", true); }
        public static void mammon(GameClient client) { client.Entity.Update(_String.Effect, "mammon", true); }
        public static void wumo_godap(GameClient client) { client.Entity.Update(_String.Effect, "wumo_godap", true); }
        public static void wumo_godcyc(GameClient client) { client.Entity.Update(_String.Effect, "wumo_godcyc", true); }
        public static void wumo_jw(GameClient client) { client.Entity.Update(_String.Effect, "wumo_jw", true); }
        public static void wumo_onap(GameClient client) { client.Entity.Update(_String.Effect, "wumo_onap", true); }
        public static void wumo_oncyc(GameClient client) { client.Entity.Update(_String.Effect, "wumo_oncyc", true); }
        public static void wumo_ondis(GameClient client) { client.Entity.Update(_String.Effect, "wumo_ondis", true); }
        public static void wumo_pdac(GameClient client) { client.Entity.Update(_String.Effect, "wumo_pdac", true); }
        public static void wumo_whi(GameClient client) { client.Entity.Update(_String.Effect, "wumo_whi", true); }
        public static void xdn_fi1(GameClient client) { client.Entity.Update(_String.Effect, "xdn_fi1", true); }
        public static void xdn_fi2(GameClient client) { client.Entity.Update(_String.Effect, "xdn_fi2", true); }
        public static void xidag_bafi(GameClient client) { client.Entity.Update(_String.Effect, "xidag_bafi", true); }
        public static void xidag_d901(GameClient client) { client.Entity.Update(_String.Effect, "xidag_d901", true); }
        public static void xidag_d902(GameClient client) { client.Entity.Update(_String.Effect, "xidag_d902", true); }
        public static void xidag_da(GameClient client) { client.Entity.Update(_String.Effect, "xidag_da", true); }
        public static void xidag_f901(GameClient client) { client.Entity.Update(_String.Effect, "xidag_f901", true); }
        public static void xidag_f902(GameClient client) { client.Entity.Update(_String.Effect, "xidag_f902", true); }
        public static void xidag_f903(GameClient client) { client.Entity.Update(_String.Effect, "xidag_f903", true); }
        public static void xidag_fcy(GameClient client) { client.Entity.Update(_String.Effect, "xidag_fcy", true); }
        public static void xnd_bat_fly(GameClient client) { client.Entity.Update(_String.Effect, "xnd_bat_fly", true); }
        public static void zfregime1(GameClient client) { client.Entity.Update(_String.Effect, "zfregime1", true); }
        public static void zfregime2(GameClient client) { client.Entity.Update(_String.Effect, "zfregime2", true); }
        public static void zfregime3(GameClient client) { client.Entity.Update(_String.Effect, "zfregime3", true); }
        public static void zfregime4(GameClient client) { client.Entity.Update(_String.Effect, "zfregime4", true); }
        public static void zhtx_attack(GameClient client) { client.Entity.Update(_String.Effect, "zhtx_attack", true); }
        public static void zs_dpgd_dong(GameClient client) { client.Entity.Update(_String.Effect, "zs_dpgd_dong", true); }
        public static void ws_hytxj_att(GameClient client) { client.Entity.Update(_String.Effect, "ws_hytxj_att", true); }
        public static void ws_hytxj_b_n(GameClient client) { client.Entity.Update(_String.Effect, "ws_hytxj_b_n", true); }
        public static void ws_hytxj_hit(GameClient client) { client.Entity.Update(_String.Effect, "ws_hytxj_hit", true); }
        public static void ws_hytxj_r_n(GameClient client) { client.Entity.Update(_String.Effect, "ws_hytxj_r_n", true); }
        public static void ws_hytxj_y_n(GameClient client) { client.Entity.Update(_String.Effect, "ws_hytxj_y_n", true); }
        public static void wsarm_electhig(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_electhig", true); }
        public static void wsarm_electlow(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_electlow", true); }
        public static void wsarm_firehig(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_firehig", true); }
        public static void wsarm_firelow(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_firelow", true); }
        public static void wsarm_goldhig(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_goldhig", true); }
        public static void wsarm_goldlow(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_goldlow", true); }
        public static void wsarm_waterhig(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_waterhig", true); }
        public static void wsarm_woodhig(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_woodhig", true); }
        public static void wsarm_woodlow(GameClient client) { client.Entity.Update(_String.Effect, "wsarm_woodlow", true); }
        public static void wsmhcxq_att(GameClient client) { client.Entity.Update(_String.Effect, "wsmhcxq_att", true); }
        public static void wsmhcxq_hit(GameClient client) { client.Entity.Update(_String.Effect, "wsmhcxq_hit", true); }
        public static void wspk_eighth(GameClient client) { client.Entity.Update(_String.Effect, "wspk_eighth", true); }
        public static void wspk_first(GameClient client) { client.Entity.Update(_String.Effect, "wspk_first", true); }
        public static void wspk_second(GameClient client) { client.Entity.Update(_String.Effect, "wspk_second", true); }
        public static void wspk_third(GameClient client) { client.Entity.Update(_String.Effect, "wspk_third", true); }
        public static void wssfs_app(GameClient client) { client.Entity.Update(_String.Effect, "wssfs_app", true); }
        public static void wssfs_cyc(GameClient client) { client.Entity.Update(_String.Effect, "wssfs_cyc", true); }
        public static void wssfs_dis(GameClient client) { client.Entity.Update(_String.Effect, "wssfs_dis", true); }
        public static void wssfs_fire(GameClient client) { client.Entity.Update(_String.Effect, "wssfs_fire", true); }
        public static void wumo_dxacc(GameClient client) { client.Entity.Update(_String.Effect, "wumo_dxacc", true); }
        public static void wumo_dxap(GameClient client) { client.Entity.Update(_String.Effect, "wumo_dxap", true); }
        public static void attack035(GameClient client) { client.Entity.Update(_String.Effect, "attack035", true); }
        public static void gddge(GameClient client) { client.Entity.Update(_String.Effect, "410239", true); }
        public static void geete(GameClient client) { client.Entity.Update(_String.Effect, "410289", true); }
        public static void ettete(GameClient client) { client.Entity.Update(_String.Effect, "410339", true); }
        public static void magic_400029_beat(GameClient client) { client.Entity.Update(_String.Effect, "magic_400029_beat", true); }
        public static void monsterbeattack_fire(GameClient client) { client.Entity.Update(_String.Effect, "monsterbeattack_fire", true); }
        public static void Status_Stop_cyc(GameClient client) { client.Entity.Update(_String.Effect, "Status_Stop_cyc", true); }
        public static void eud_431_2(GameClient client) { client.Entity.Update(_String.Effect, "eud_431_2", true); }
        public static void noconfirm096(GameClient client) { client.Entity.Update(_String.Effect, "noconfirm096", true); }
        public static void wyattack(GameClient client) { client.Entity.Update(_String.Effect, "wyattack", true); }
        public static void clewarbignor(GameClient client) { client.Entity.Update(_String.Effect, "clewarbignor", true); }
        public static void clewarbigred(GameClient client) { client.Entity.Update(_String.Effect, "clewarbigred", true); }
        public static void clewarsmall(GameClient client) { client.Entity.Update(_String.Effect, "clewarsmall", true); }
        public static void ninjapk_third(GameClient client) { client.Entity.Update(_String.Effect, "ninjapk_third", true); }
        public static void tread_ref(GameClient client) { client.Entity.Update(_String.Effect, "tread_ref", true); }
        public static void ninjia_superc(GameClient client) { client.Entity.Update(_String.Effect, "ninjia_superc", true); }
        public static void trojanpk_eight(GameClient client) { client.Entity.Update(_String.Effect, "trojanpk_eight", true); }
        public static void ninjia_superc1(GameClient client) { client.Entity.Update(_String.Effect, "ninjia_superc1", true); }
        public static void trojanpk_second(GameClient client) { client.Entity.Update(_String.Effect, "trojanpk_second", true); }
        public static void ord_fir(GameClient client) { client.Entity.Update(_String.Effect, "ord_fir", true); }
        public static void trojanpk_third(GameClient client) { client.Entity.Update(_String.Effect, "trojanpk_third", true); }
        public static void ord_sec(GameClient client) { client.Entity.Update(_String.Effect, "ord_sec", true); }
        public static void tulip_flower_charm1(GameClient client) { client.Entity.Update(_String.Effect, "tulip-flower-charm1", true); }
        public static void ord_thi(GameClient client) { client.Entity.Update(_String.Effect, "ord_thi", true); }
        public static void tulip_flower_charm2(GameClient client) { client.Entity.Update(_String.Effect, "tulip-flower-charm2", true); }
        public static void partbehit(GameClient client) { client.Entity.Update(_String.Effect, "partbehit", true); }
        public static void tulip_flower_charm3(GameClient client) { client.Entity.Update(_String.Effect, "tulip-flower-charm3", true); }
        public static void partbehithead(GameClient client) { client.Entity.Update(_String.Effect, "partbehithead", true); }
        public static void tulip_flower_full(GameClient client) { client.Entity.Update(_String.Effect, "tulip-flower-full", true); }
        public static void pigeon(GameClient client) { client.Entity.Update(_String.Effect, "pigeon", true); }
        public static void tulip_flower_g_1(GameClient client) { client.Entity.Update(_String.Effect, "tulip-flower-g-1", true); }
        public static void pir_non_dre(GameClient client) { client.Entity.Update(_String.Effect, "pir_non_dre", true); }
        public static void tulip_flower_rain(GameClient client) { client.Entity.Update(_String.Effect, "tulip-flower-rain", true); }
        public static void piratenonsuch(GameClient client) { client.Entity.Update(_String.Effect, "piratenonsuch", true); }
        public static void WarFlagEscortSuc(GameClient client) { client.Entity.Update(_String.Effect, "WarFlagEscortSuc", true); }
        public static void moveadding(GameClient client) { client.Entity.Update(_String.Effect, "moveadding", true); }
        public static void stipple_bdh(GameClient client) { client.Entity.Update(_String.Effect, "stipple_bdh", true); }
        public static void moveallay(GameClient client) { client.Entity.Update(_String.Effect, "moveallay", true); }
        public static void stipple_dhz(GameClient client) { client.Entity.Update(_String.Effect, "stipple_dhz", true); }
        public static void moveallaying(GameClient client) { client.Entity.Update(_String.Effect, "moveallaying", true); }
        public static void stipple_jx(GameClient client) { client.Entity.Update(_String.Effect, "stipple_jx", true); }
        public static void new_goods_tips(GameClient client) { client.Entity.Update(_String.Effect, "new_goods_tips", true); }
        public static void stipple_kdh(GameClient client) { client.Entity.Update(_String.Effect, "stipple_kdh", true); }
        public static void NEW_flower_charm1(GameClient client) { client.Entity.Update(_String.Effect, "NEW-flower-charm1", true); }
        public static void suc_sys_fun(GameClient client) { client.Entity.Update(_String.Effect, "suc_sys_fun", true); }
        public static void NEW_flower_charm2(GameClient client) { client.Entity.Update(_String.Effect, "NEW-flower-charm2", true); }
        public static void switchitem(GameClient client) { client.Entity.Update(_String.Effect, "switchitem", true); }
        public static void NEW_flower_charm3(GameClient client) { client.Entity.Update(_String.Effect, "NEW-flower-charm3", true); }
        public static void TakeOnLilySuit(GameClient client) { client.Entity.Update(_String.Effect, "TakeOnLilySuit", true); }
        public static void NEW_flower_full(GameClient client) { client.Entity.Update(_String.Effect, "NEW-flower-full", true); }
        public static void TakeOnOrchisSuit(GameClient client) { client.Entity.Update(_String.Effect, "TakeOnOrchisSuit", true); }
        public static void NEW_flower_g_1(GameClient client) { client.Entity.Update(_String.Effect, "NEW-flower-g-1", true); }
        public static void TakeOnRoseSuit(GameClient client) { client.Entity.Update(_String.Effect, "TakeOnRoseSuit", true); }
        public static void NEW_flower_r_1(GameClient client) { client.Entity.Update(_String.Effect, "NEW-flower-r-1", true); }
        public static void TakeOnTulipSuit(GameClient client) { client.Entity.Update(_String.Effect, "TakeOnTulipSuit", true); }
        public static void NEW_flower_rain(GameClient client) { client.Entity.Update(_String.Effect, "NEW-flower-rain", true); }
        public static void targetshit(GameClient client) { client.Entity.Update(_String.Effect, "targetshit", true); }
        public static void newmonbro(GameClient client) { client.Entity.Update(_String.Effect, "newmonbro", true); }
        public static void taskcomplete(GameClient client) { client.Entity.Update(_String.Effect, "taskcomplete", true); }
        public static void Ninja120(GameClient client) { client.Entity.Update(_String.Effect, "Ninja120", true); }
        public static void TaskFail(GameClient client) { client.Entity.Update(_String.Effect, "TaskFail", true); }
        public static void ninjapk_eight(GameClient client) { client.Entity.Update(_String.Effect, "ninjapk_eight", true); }
        public static void taskhalf(GameClient client) { client.Entity.Update(_String.Effect, "taskhalf", true); }
        public static void ninjapk_second(GameClient client) { client.Entity.Update(_String.Effect, "ninjapk_second", true); }
        public static void tread_acc(GameClient client) { client.Entity.Update(_String.Effect, "tread_acc", true); }
        public static void mortuary_bedbug1(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_bedbug1", true); }
        public static void spoondrift01(GameClient client) { client.Entity.Update(_String.Effect, "spoondrift01", true); }
        public static void mortuary_bedbug2(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_bedbug2", true); }
        public static void sports_failure(GameClient client) { client.Entity.Update(_String.Effect, "sports_failure", true); }
        public static void mortuary_cobweb1(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_cobweb1", true); }
        public static void sports_victory(GameClient client) { client.Entity.Update(_String.Effect, "sports_victory", true); }
        public static void mortuary_cobweb2(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_cobweb2", true); }
        public static void sprayatt914(GameClient client) { client.Entity.Update(_String.Effect, "sprayatt914", true); }
        public static void mortuary_roach1(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_roach1", true); }
        public static void sscg_cjj_hitg(GameClient client) { client.Entity.Update(_String.Effect, "sscg_cjj_hitg", true); }
        public static void mortuary_roach2(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_roach2", true); }
        public static void ssch_wlhd_fir(GameClient client) { client.Entity.Update(_String.Effect, "ssch_wlhd_fir", true); }
        public static void mortuary_soul1(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_soul1", true); }
        public static void ssch_wlhd_hit(GameClient client) { client.Entity.Update(_String.Effect, "ssch_wlhd_hit", true); }
        public static void mortuary_soul2(GameClient client) { client.Entity.Update(_String.Effect, "mortuary_soul2", true); }
        public static void sscs_htsd_app(GameClient client) { client.Entity.Update(_String.Effect, "sscs_htsd_app", true); }
        public static void move_continue(GameClient client) { client.Entity.Update(_String.Effect, "move_continue", true); }
        public static void sscs_htsd_cyc(GameClient client) { client.Entity.Update(_String.Effect, "sscs_htsd_cyc", true); }
        public static void move_improve(GameClient client) { client.Entity.Update(_String.Effect, "move_improve", true); }
        public static void sscs_htsd_dis(GameClient client) { client.Entity.Update(_String.Effect, "sscs_htsd_dis", true); }
        public static void moveadd(GameClient client) { client.Entity.Update(_String.Effect, "moveadd", true); }
        public static void statusweak(GameClient client) { client.Entity.Update(_String.Effect, "statusweak", true); }
        public static void longpi5_452(GameClient client) { client.Entity.Update(_String.Effect, "longpi5_452", true); }
        public static void sea_ver_fir(GameClient client) { client.Entity.Update(_String.Effect, "sea_ver_fir", true); }
        public static void longpi6_452(GameClient client) { client.Entity.Update(_String.Effect, "longpi6_452", true); }
        public static void sea_ver_sec(GameClient client) { client.Entity.Update(_String.Effect, "sea_ver_sec", true); }
        public static void longpi7_452(GameClient client) { client.Entity.Update(_String.Effect, "longpi7_452", true); }
        public static void sea_ver_thi(GameClient client) { client.Entity.Update(_String.Effect, "sea_ver_thi", true); }
        public static void longpi8_452(GameClient client) { client.Entity.Update(_String.Effect, "longpi8_452", true); }
        public static void seismatt_01(GameClient client) { client.Entity.Update(_String.Effect, "seismatt_01", true); }
        public static void seismatt_02(GameClient client) { client.Entity.Update(_String.Effect, "seismatt_02", true); }
        public static void mate_pk_01(GameClient client) { client.Entity.Update(_String.Effect, "mate_pk_01", true); }
        public static void seismatt_03(GameClient client) { client.Entity.Update(_String.Effect, "seismatt_03", true); }
        public static void mate_pk_02(GameClient client) { client.Entity.Update(_String.Effect, "mate_pk_02", true); }
        public static void sen_gif_col(GameClient client) { client.Entity.Update(_String.Effect, "sen_gif_col", true); }
        public static void mate_pk_03(GameClient client) { client.Entity.Update(_String.Effect, "mate_pk_03", true); }
        public static void sen_gif_ful(GameClient client) { client.Entity.Update(_String.Effect, "sen_gif_ful", true); }
        public static void mate_pk_08(GameClient client) { client.Entity.Update(_String.Effect, "mate_pk_08", true); }
        public static void sen_gif_sen(GameClient client) { client.Entity.Update(_String.Effect, "sen_gif_sen", true); }
        public static void minmapflag(GameClient client) { client.Entity.Update(_String.Effect, "minmapflag", true); }
        public static void sex_pk_gir(GameClient client) { client.Entity.Update(_String.Effect, "sex_pk_gir", true); }
        public static void end_task(GameClient client) { client.Entity.Update(_String.Effect, "end_task", true); }
        public static void monkalnonsuch(GameClient client) { client.Entity.Update(_String.Effect, "monkalnonsuch", true); }
        public static void sex_pk_man(GameClient client) { client.Entity.Update(_String.Effect, "sex_pk_man", true); }
        public static void monkalnonsuch1(GameClient client) { client.Entity.Update(_String.Effect, "monkalnonsuch1", true); }
        public static void ShieldBlock(GameClient client) { client.Entity.Update(_String.Effect, "ShieldBlock", true); }
        public static void moonpk_eight(GameClient client) { client.Entity.Update(_String.Effect, "moonpk_eight", true); }
        public static void slowliquid(GameClient client) { client.Entity.Update(_String.Effect, "slowliquid", true); }
        public static void moonpk_second(GameClient client) { client.Entity.Update(_String.Effect, "moonpk_second", true); }
        public static void s_motive_surf02(GameClient client) { client.Entity.Update(_String.Effect, "s-motive-surf02", true); }
        public static void moonpk_third(GameClient client) { client.Entity.Update(_String.Effect, "moonpk_third", true); }
        public static void s_motive_surf03(GameClient client) { client.Entity.Update(_String.Effect, "s-motive-surf03", true); }
        public static void jypk130up_js(GameClient client) { client.Entity.Update(_String.Effect, "jypk130up_js", true); }
        public static void riga_flacc(GameClient client) { client.Entity.Update(_String.Effect, "riga_flacc", true); }
        public static void jypk130up_th(GameClient client) { client.Entity.Update(_String.Effect, "jypk130up_th", true); }
        public static void riga_flap(GameClient client) { client.Entity.Update(_String.Effect, "riga_flap", true); }
        public static void jypk130up_zy(GameClient client) { client.Entity.Update(_String.Effect, "jypk130up_zy", true); }
        public static void rockdownatt(GameClient client) { client.Entity.Update(_String.Effect, "rockdownatt", true); }
        public static void lighbo(GameClient client) { client.Entity.Update(_String.Effect, "lighbo", true); }
        public static void roundrobingw(GameClient client) { client.Entity.Update(_String.Effect, "roundrobingw", true); }
        public static void lighls(GameClient client) { client.Entity.Update(_String.Effect, "lighls", true); }
        public static void runoffingw(GameClient client) { client.Entity.Update(_String.Effect, "runoffingw", true); }
        public static void longci4_453(GameClient client) { client.Entity.Update(_String.Effect, "longci4_453", true); }
        public static void scene_bedbladder(GameClient client) { client.Entity.Update(_String.Effect, "scene_bedbladder", true); }
        public static void longci5_453(GameClient client) { client.Entity.Update(_String.Effect, "longci5_453", true); }
        public static void scene_largefish(GameClient client) { client.Entity.Update(_String.Effect, "scene_largefish", true); }
        public static void longci6_453(GameClient client) { client.Entity.Update(_String.Effect, "longci6_453", true); }
        public static void scene_transmissions(GameClient client) { client.Entity.Update(_String.Effect, "scene_transmissions", true); }
        public static void longci7_453(GameClient client) { client.Entity.Update(_String.Effect, "longci7_453", true); }
        public static void scholar(GameClient client) { client.Entity.Update(_String.Effect, "scholar", true); }
        public static void longci8_453(GameClient client) { client.Entity.Update(_String.Effect, "longci8_453", true); }
        public static void sea_mis_eff(GameClient client) { client.Entity.Update(_String.Effect, "sea_mis_eff", true); }
        public static void longpi4_452(GameClient client) { client.Entity.Update(_String.Effect, "longpi4_452", true); }
        public static void sea_ver_eig(GameClient client) { client.Entity.Update(_String.Effect, "sea_ver_eig", true); }
        public static void jsb_rayg_fir(GameClient client) { client.Entity.Update(_String.Effect, "jsb_rayg_fir", true); }
        public static void property_wood(GameClient client) { client.Entity.Update(_String.Effect, "property_wood", true); }
        public static void jsb_rayg_hit(GameClient client) { client.Entity.Update(_String.Effect, "jsb_rayg_hit", true); }
        public static void ptjeff_pul(GameClient client) { client.Entity.Update(_String.Effect, "ptjeff_pul", true); }
        public static void jsb_reva_att(GameClient client) { client.Entity.Update(_String.Effect, "jsb_reva_att", true); }
        public static void rank(GameClient client) { client.Entity.Update(_String.Effect, "rank", true); }
        public static void jsb_reva_fir(GameClient client) { client.Entity.Update(_String.Effect, "jsb_reva_fir", true); }
        public static void rdeltoid_app(GameClient client) { client.Entity.Update(_String.Effect, "rdeltoid_app", true); }
        public static void jsb_reva_hit(GameClient client) { client.Entity.Update(_String.Effect, "jsb_reva_hit", true); }
        public static void rdeltoid_cyc(GameClient client) { client.Entity.Update(_String.Effect, "rdeltoid_cyc", true); }
        public static void jsb_reva_pre(GameClient client) { client.Entity.Update(_String.Effect, "jsb_reva_pre", true); }
        public static void rdeltoid_dis(GameClient client) { client.Entity.Update(_String.Effect, "rdeltoid_dis", true); }
        public static void jsb_reva_sin(GameClient client) { client.Entity.Update(_String.Effect, "jsb_reva_sin", true); }
        public static void replymove(GameClient client) { client.Entity.Update(_String.Effect, "replymove", true); }
        public static void jsb_skyg_att(GameClient client) { client.Entity.Update(_String.Effect, "jsb_skyg_att", true); }
        public static void RichGod_Money(GameClient client) { client.Entity.Update(_String.Effect, "RichGod_Money", true); }
        public static void jsb_skyg_pre(GameClient client) { client.Entity.Update(_String.Effect, "jsb_skyg_pre", true); }
        public static void ride_down(GameClient client) { client.Entity.Update(_String.Effect, "ride_down", true); }
        public static void juren(GameClient client) { client.Entity.Update(_String.Effect, "juren", true); }
        public static void ride_faint(GameClient client) { client.Entity.Update(_String.Effect, "ride_faint", true); }
        public static void jypk130down_gs(GameClient client) { client.Entity.Update(_String.Effect, "jypk130down_gs", true); }
        public static void ride_odd(GameClient client) { client.Entity.Update(_String.Effect, "ride_odd", true); }
        public static void jypk130down_hy(GameClient client) { client.Entity.Update(_String.Effect, "jypk130down_hy", true); }
        public static void ride_screen(GameClient client) { client.Entity.Update(_String.Effect, "ride_screen", true); }
        public static void jypk130down_jr(GameClient client) { client.Entity.Update(_String.Effect, "jypk130down_jr", true); }
        public static void ride_suck(GameClient client) { client.Entity.Update(_String.Effect, "ride_suck", true); }
        public static void m1(GameClient client) { client.Entity.Update(_String.Effect, "m1", true); }
        public static void jypk130down_xc(GameClient client) { client.Entity.Update(_String.Effect, "jypk130down_xc", true); }
        public static void ride_up(GameClient client) { client.Entity.Update(_String.Effect, "ride_up", true); }
        public static void m2(GameClient client) { client.Entity.Update(_String.Effect, "m2", true); }
        public static void jypk130up_by(GameClient client) { client.Entity.Update(_String.Effect, "jypk130up_by", true); }
        public static void RideMatchArrive(GameClient client) { client.Entity.Update(_String.Effect, "RideMatchArrive", true); }
        public static void istabhit_dis(GameClient client) { client.Entity.Update(_String.Effect, "istabhit_dis", true); }
        public static void pkjinj_ll5(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_ll5", true); }
        public static void white_flower_full(GameClient client) { client.Entity.Update(_String.Effect, "white-flower-full", true); }
        public static void istabind(GameClient client) { client.Entity.Update(_String.Effect, "istabind", true); }
        public static void pkjinj_lr1(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_lr1", true); }
        public static void white_flower_g_1(GameClient client) { client.Entity.Update(_String.Effect, "white-flower-g-1", true); }
        public static void jinshi(GameClient client) { client.Entity.Update(_String.Effect, "jinshi", true); }
        public static void pkjinj_lr2(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_lr2", true); }
        public static void white_flower_rain(GameClient client) { client.Entity.Update(_String.Effect, "white-flower-rain", true); }
        public static void jsb_1eddy_hit(GameClient client) { client.Entity.Update(_String.Effect, "jsb_1eddy_hit", true); }
        public static void pkjinj_lr3(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_lr3", true); }
        public static void windupatt907(GameClient client) { client.Entity.Update(_String.Effect, "windupatt907", true); }
        public static void jsb_1eddy_zan(GameClient client) { client.Entity.Update(_String.Effect, "jsb_1eddy_zan", true); }
        public static void pkjinj_lr4(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_lr4", true); }
        public static void winnlock1(GameClient client) { client.Entity.Update(_String.Effect, "winnlock1", true); }
        public static void jsb_gst01_app(GameClient client) { client.Entity.Update(_String.Effect, "jsb_gst01_app", true); }
        public static void pkjinj_lr5(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_lr5", true); }
        public static void winnlock2(GameClient client) { client.Entity.Update(_String.Effect, "winnlock2", true); }
        public static void jsb_gst01_cyc(GameClient client) { client.Entity.Update(_String.Effect, "jsb_gst01_cyc", true); }
        public static void pkjinj_xl1(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_xl1", true); }
        public static void worryatt401(GameClient client) { client.Entity.Update(_String.Effect, "worryatt401", true); }
        public static void jsb_gst01_dis(GameClient client) { client.Entity.Update(_String.Effect, "jsb_gst01_dis", true); }
        public static void property_fire(GameClient client) { client.Entity.Update(_String.Effect, "property_fire", true); }
        public static void ws_ffwys_fire(GameClient client) { client.Entity.Update(_String.Effect, "ws_ffwys_fire", true); }
        public static void jsb_gst02_app(GameClient client) { client.Entity.Update(_String.Effect, "jsb_gst02_app", true); }
        public static void property_gold(GameClient client) { client.Entity.Update(_String.Effect, "property_gold", true); }
        public static void ws_ffwys_hand01(GameClient client) { client.Entity.Update(_String.Effect, "ws_ffwys_hand01", true); }
        public static void jsb_gst02_cyc(GameClient client) { client.Entity.Update(_String.Effect, "jsb_gst02_cyc", true); }
        public static void property_soil(GameClient client) { client.Entity.Update(_String.Effect, "property_soil", true); }
        public static void ws_ffwys_hand02(GameClient client) { client.Entity.Update(_String.Effect, "ws_ffwys_hand02", true); }
        public static void jsb_gst02_dis(GameClient client) { client.Entity.Update(_String.Effect, "jsb_gst02_dis", true); }
        public static void property_water(GameClient client) { client.Entity.Update(_String.Effect, "property_water", true); }
        public static void ws_ffwys_ploy(GameClient client) { client.Entity.Update(_String.Effect, "ws_ffwys_ploy", true); }
        public static void iarrowhg_cyc(GameClient client) { client.Entity.Update(_String.Effect, "iarrowhg_cyc", true); }
        public static void pk_ble_bea(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_bea", true); }
        public static void warflagsubmit(GameClient client) { client.Entity.Update(_String.Effect, "warflagsubmit", true); }
        public static void iarrowhg_dis(GameClient client) { client.Entity.Update(_String.Effect, "iarrowhg_dis", true); }
        public static void pk_ble_bow(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_bow", true); }
        public static void warriorpk_eight(GameClient client) { client.Entity.Update(_String.Effect, "warriorpk_eight", true); }
        public static void iboss_attack(GameClient client) { client.Entity.Update(_String.Effect, "iboss_attack", true); }
        public static void pk_ble_fie(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_fie", true); }
        public static void warriorpk_second(GameClient client) { client.Entity.Update(_String.Effect, "warriorpk_second", true); }
        public static void iboss_claw401(GameClient client) { client.Entity.Update(_String.Effect, "iboss_claw401", true); }
        public static void pk_ble_fla(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_fla", true); }
        public static void warriorpk_third(GameClient client) { client.Entity.Update(_String.Effect, "warriorpk_third", true); }
        public static void iboss_fleghit(GameClient client) { client.Entity.Update(_String.Effect, "iboss_fleghit", true); }
        public static void pk_ble_pir(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_pir", true); }
        public static void waterpk_eight(GameClient client) { client.Entity.Update(_String.Effect, "waterpk_eight", true); }
        public static void iboss_ibutfly(GameClient client) { client.Entity.Update(_String.Effect, "iboss_ibutfly", true); }
        public static void pk_ble_sol(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_sol", true); }
        public static void waterpk_second(GameClient client) { client.Entity.Update(_String.Effect, "waterpk_second", true); }
        public static void iboss_ibuthit(GameClient client) { client.Entity.Update(_String.Effect, "iboss_ibuthit", true); }
        public static void pk_ble_war(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_war", true); }
        public static void waterpk_third(GameClient client) { client.Entity.Update(_String.Effect, "waterpk_third", true); }
        public static void improveSuc(GameClient client) { client.Entity.Update(_String.Effect, "improveSuc", true); }
        public static void pk_ble_wat(GameClient client) { client.Entity.Update(_String.Effect, "pk_ble_wat", true); }
        public static void wbonze_fire(GameClient client) { client.Entity.Update(_String.Effect, "wbonze_fire", true); }
        public static void isallyf_app(GameClient client) { client.Entity.Update(_String.Effect, "isallyf_app", true); }
        public static void pk_dra_ble(GameClient client) { client.Entity.Update(_String.Effect, "pk_dra_ble", true); }
        public static void wbonze_state(GameClient client) { client.Entity.Update(_String.Effect, "wbonze_state", true); }
        public static void isallyf_cyc(GameClient client) { client.Entity.Update(_String.Effect, "isallyf_cyc", true); }
        public static void PK_resources(GameClient client) { client.Entity.Update(_String.Effect, "PK_resources", true); }
        public static void weekpk_eight(GameClient client) { client.Entity.Update(_String.Effect, "weekpk_eight", true); }
        public static void isallyf_dis(GameClient client) { client.Entity.Update(_String.Effect, "isallyf_dis", true); }
        public static void PKchampion(GameClient client) { client.Entity.Update(_String.Effect, "PKchampion", true); }
        public static void weekpk_second(GameClient client) { client.Entity.Update(_String.Effect, "weekpk_second", true); }
        public static void isallyhit(GameClient client) { client.Entity.Update(_String.Effect, "isallyhit", true); }
        public static void pkjinj_ll1(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_ll1", true); }
        public static void weekpk_third(GameClient client) { client.Entity.Update(_String.Effect, "weekpk_third", true); }
        public static void isallyind(GameClient client) { client.Entity.Update(_String.Effect, "isallyind", true); }
        public static void pkjinj_ll2(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_ll2", true); }
        public static void white_flower_char(GameClient client) { client.Entity.Update(_String.Effect, "white-flower-char", true); }
        public static void istabhit_app(GameClient client) { client.Entity.Update(_String.Effect, "istabhit_app", true); }
        public static void pkjinj_ll3(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_ll3", true); }
        public static void istabhit_cyc(GameClient client) { client.Entity.Update(_String.Effect, "istabhit_cyc", true); }
        public static void pkjinj_ll4(GameClient client) { client.Entity.Update(_String.Effect, "pkjinj_ll4", true); }
        public static void havefit(GameClient client) { client.Entity.Update(_String.Effect, "havefit", true); }
        public static void hideperson(GameClient client) { client.Entity.Update(_String.Effect, "hideperson", true); }
        public static void hot_goods_tips(GameClient client) { client.Entity.Update(_String.Effect, "hot_goods_tips", true); }
        public static void iarrow_915(GameClient client) { client.Entity.Update(_String.Effect, "iarrow_915", true); }
        public static void iarrow_916(GameClient client) { client.Entity.Update(_String.Effect, "iarrow_916", true); }
        public static void iarrow_917(GameClient client) { client.Entity.Update(_String.Effect, "iarrow_917", true); }
        public static void iarrowhg_app(GameClient client) { client.Entity.Update(_String.Effect, "iarrowhg_app", true); }
        public static void get_special_dancer(GameClient client) { client.Entity.Update(_String.Effect, "get_special_dancer", true); }
        public static void GetAchi(GameClient client) { client.Entity.Update(_String.Effect, "GetAchi", true); }
        public static void girlassist_fir(GameClient client) { client.Entity.Update(_String.Effect, "girlassist_fir", true); }
        public static void girlassist_sec(GameClient client) { client.Entity.Update(_String.Effect, "girlassist_sec", true); }
        public static void girlassist_thi(GameClient client) { client.Entity.Update(_String.Effect, "girlassist_thi", true); }
        public static void god_buj1(GameClient client) { client.Entity.Update(_String.Effect, "god_buj1", true); }
        public static void god_buj2(GameClient client) { client.Entity.Update(_String.Effect, "god_buj2", true); }
        public static void frost_end(GameClient client) { client.Entity.Update(_String.Effect, "frost_end", true); }
        public static void gam_acc(GameClient client) { client.Entity.Update(_String.Effect, "gam_acc", true); }
        public static void gam_buss(GameClient client) { client.Entity.Update(_String.Effect, "gam_buss", true); }
        public static void gam_buss_ap(GameClient client) { client.Entity.Update(_String.Effect, "gam_buss_ap", true); }
        public static void gam_buss_cyc(GameClient client) { client.Entity.Update(_String.Effect, "gam_buss_cyc", true); }
        public static void gam_buss_end(GameClient client) { client.Entity.Update(_String.Effect, "gam_buss_end", true); }
        public static void gam_cuddle_ap(GameClient client) { client.Entity.Update(_String.Effect, "gam_cuddle_ap", true); }
        public static void factionbul_input(GameClient client) { client.Entity.Update(_String.Effect, "factionbul_input", true); }
        public static void factionbul_succ(GameClient client) { client.Entity.Update(_String.Effect, "factionbul_succ", true); }
        public static void fam_exp(GameClient client) { client.Entity.Update(_String.Effect, "fam_exp", true); }
        public static void fam_exp_special(GameClient client) { client.Entity.Update(_String.Effect, "fam_exp_special", true); }
        public static void fam_gain(GameClient client) { client.Entity.Update(_String.Effect, "fam_gain", true); }
        public static void fam_gain_special(GameClient client) { client.Entity.Update(_String.Effect, "fam_gain_special", true); }
        public static void fanpcse(GameClient client) { client.Entity.Update(_String.Effect, "fanpcse", true); }
        public static void dealfly1(GameClient client) { client.Entity.Update(_String.Effect, "dealfly1", true); }
        public static void dealfly2(GameClient client) { client.Entity.Update(_String.Effect, "dealfly2", true); }
        public static void dealfly3(GameClient client) { client.Entity.Update(_String.Effect, "dealfly3", true); }
        public static void dealfly4(GameClient client) { client.Entity.Update(_String.Effect, "dealfly4", true); }
        public static void dealfly5(GameClient client) { client.Entity.Update(_String.Effect, "dealfly5", true); }
        public static void dealfly6(GameClient client) { client.Entity.Update(_String.Effect, "dealfly6", true); }
        public static void dealfly7(GameClient client) { client.Entity.Update(_String.Effect, "dealfly7", true); }
        public static void gamebow(GameClient client) { client.Entity.Update(_String.Effect, "gamebow", true); }
        public static void halo_huo_fir(GameClient client) { client.Entity.Update(_String.Effect, "halo_huo_fir", true); }
        #endregion
    }
}
